### ISSUE TITLE
Suggesting autogenerated Documentation

### ISSUE THREAD

**Issue by Jimut123** [sarvottamananda/autoworld#6]
Perhaps use [doxygen](https://www.doxygen.nl/index.html) or [breathe](https://breathe.readthedocs.io/en/latest/) to generate the documentation for the tutorials. Can test this feature. Though [sphinx-doc](https://www.sphinx-doc.org/en/master/contents.html) is good, but not supported for C++ documentation.

**Comment by sarvottamananda** [comment]
If you want to add documentation, you go ahead. I myself think that the code is too simple to warrant the effort. Only tut5 might require some explanations, But others don't.

**Comment by sarvottamananda** [comment]
Actually I am waiting for technology to advance so that we have two way documentation. Documentation in code should show in the documentation tool, and a wiki like changes in documentation tool should reflect back to code. If we can have something like that it would be great.

**Comment by sarvottamananda** [comment]
Jimut If you want you can take up this work. I will close the ticket.
